### ISSUE TITLE
uninitialized constant AccountsController::ShopifyIntegration

### ISSUE THREAD

**Issue by igwtsoftware** [mikelarkin/contestapp#2]
When I click the Test Connection button I get this error: "uninitialized constant AccountsController::ShopifyIntegration".

I googled and there are several people stuck on this error. (amazon)

After the shopify_integration.rb file is added to app/services/ should I do anything on the command line for it to be detected?

**Comment by RossUK88** [comment]
I am having the same problem, used the code from the github pages and I'm still having the same problems.

uninitialized constant AccountsController::ShopifyIntegration

**Comment by mikelarkin** [comment]
Are you saving the code from https://github.com/mikelarkin/contestapp/blob/chapter_03/app/services/shopify_integration.rb

into the proper location?  It needs to go into /app/services/shopify_integration.rb

**Comment by RossUK88** [comment]
Yes that code was copied in and in the correct place.
I've just downloaded the whole of the chapter 3 branch from Git and copied the app/ folder over and it now works. So there must have been something wrong in another file in there, I assume one of the controllers.

Thanks

**Comment by mikelarkin** [comment]
Ok, then likely that means the class wasn't being included correctly.  Glad
you figured it out, sorry for the hassle!


Thanks,

Mike
mjlarkin@gmail.com
617-697-1176

From:  RossUK88 <notifications@github.com>
Reply-To:  mikelarkin/contestapp
<reply+00004809fd9f63b4a147067bcec121105b84a3dbfbfa071692cf0000000110fd6f129
2a169ce02fe376c@reply.github.com>
Date:  Thursday, February 19, 2015 at 4:29 AM
To:  mikelarkin/contestapp <contestapp@noreply.github.com>
Cc:  Michael Larkin <mjlarkin@gmail.com>
Subject:  Re: [contestapp] uninitialized constant
AccountsController::ShopifyIntegration (#2)


Yes that code was copied in and in the correct place.
I've just downloaded the whole of the chapter 3 branch from Git and copied
the app/ folder over and it now works. So there must have been something
wrong in another file in there, I assume one of the controllers.

Thanks

‹
Reply to this email directly or view it on GitHub
<https://github.com/mikelarkin/contestapp/issues/2#issuecomment-75020942> .
