### ISSUE TITLE
Issues with copying specs from this repository

### ISSUE THREAD

**Issue by marat00** [mikelarkin/contestapp#3]
Hello Mike,

I am not sure if this is worth mentioning, but copying specs from this repository would not work without copying the whole project or explicitly sticking to Rspec 2.x in the gemfile, because of syntax changes between Rspec 2.x (that was used in your project) and Rspec 3.x (that will be installed when someone creates a Gemfile identical to yours in the book). Have you considered updating your code for Rspec 3.x or would you rather recommend to stick with Rspec 2.x until the end to avoid any compatibility issues.

**Comment by mikelarkin** [comment]
Good catch, thanks!  I locked the gem version.
